apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc
spec:
  volumeName: host-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources: # which resources we want to get for this claim
    requests:
      storage: 1Gi # should not request for more than available storage

